### ISSUE TITLE
Endpoint used to find builds is deprecated and defunct

### ISSUE THREAD

**Issue by joerghall** [NLueg/node-java-connector#10]
The API used to find the build has been deprecated and appears to be defunct.

60: let url = 'https://api.adoptopenjdk.net/v2/info/releases/openjdk' + version + '?'

The new API is version 3 and can be found here. https://api.adoptopenjdk.net/q/swagger-ui/

**Comment by NLueg** [comment]
Thank you for submitting the issue! I will have a look into it.
