### ISSUE TITLE
Error: ENOTDIR: not a directory when running inside of electron

### ISSUE THREAD

**Issue by Zettervall** [NLueg/node-java-connector#8]
Hi,
Im using node-java-connector 0.2.1 trying to download a jre inside a electron app I get:

Error: ENOTDIR, not a directory
    at createError (electron/js2c/asar_bundle.js:5:1382)
    at Object.e.mkdir (electron/js2c/asar_bundle.js:5:11735)
    at C:\Program Files\app\resources\app.asar\node_modules\node-java-connector\dist\index.js:310:20
    at electron/js2c/asar_bundle.js:5:507
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ENOTDIR',
  errno: -20
}

I assume it is because __dirname is within some kind of electron package. 

If I assign __dirname to another tmp dir I can get it to work, but I would like to not have to assign __dirname to anything. 

Feature request:
It would be nice if the tmp directory node-java-connector uses when running was possible to override with a parameter. 
I can create a pull request if you think this is a good idea and dont want to implement it yourself.

Best regards,
Oskar

**Comment by NLueg** [comment]
Hey @Zettervall,
thanks for submitting the issue with a potential fix.
If you still need this feature, I would be very happy if you could create a pull request that solves the issue.

**Comment by NLueg** [comment]
Closed by #12.
The fix is published as version `1.1.0`.

**Comment by NLueg** [comment]
Closed by #12.
The fix is published as version `1.1.0`.
